# Generated by Django 3.2 on 2024-02-03 18:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_capture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='url_capture'),
        ),
    ]
