# Generated by Django 3.2 on 2024-02-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tecnologies',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
